### ISSUE TITLE
[Question] Bot Message Icons

### ISSUE THREAD

**Issue by ghost** [scalableminds/chatroom#32]
Hello,

Is there an option to add in icons for the message bubbles? For example, I'd like to put in a custom image next to each of the bot responses. If I were to do this myself, would I need to make the changes within `messages.js` or within `chatroom.js`?

Thank you

**Comment by normanrz** [comment]
Hi, there is no support for icons yet. If you know React and CSS, you could try adding it yourself. I'd be happy to review the PR.
I'd probably implement it in the `MessageGroup` within the `chatroom.js`, because then there will be only one icon per block of messages (like in fb messenger): https://github.com/scalableminds/chatroom/blob/master/src/Chatroom.js#L44

**Comment by smasschelin** [comment]
I'll give it a look. I'm fairly new to React, but I'll give it a shot.

**Comment by kmanadkat** [comment]
hey @smasschelin , you donot need React or infact Js knowledge for this. Just modify css :)

<img width="401" alt="Screenshot 2021-04-14 at 12 41 42 PM" src="https://user-images.githubusercontent.com/25281055/114668957-fa5e5d00-9d1e-11eb-9d17-65a778fccf7d.png">

```css
.chatroom .chats .chat.left::before{
  content: '';
  visibility: visible;
  background-image: url('../imgs/Bot-Icon.png');
  background-size: contain;
  background-repeat: no-repeat;
  display: block;
  height: 26px;
  width: 26px;
  position: absolute;
  top: -16px;
  left: -28px;  
  /* box-shadow: 0px 2px 3px 0px #715e8b28; */
}
```

If you want to checkout other customizations like user image, colors etc. then you can see [here](https://github.com/kmanadkat/rasa-wellness-bot/blob/master/demo/assets/css/Chatroom.css) 

Hope this helps. 

@hotzenklotz I am good with react, let me see if I can add this feature so that users can put image in properties along with other params.
